### ISSUE TITLE
Implement Vault plugin mechanism to return data asset credentials from OpenMetadata 

### ISSUE THREAD

**Issue by roytman** [fybrik/openmetadata-connector#20]
OMD catalog in the `getAssetInfo` call returns a vault path to the data asset credentials. 
Fybrik modules ask vault to get these credentials. We need to implement a vault plugin to achieve the credentials from OMD.

**Comment by cdoron** [comment]
Completed: https://github.com/fybrik/vault-plugin-secrets-kubernetes-reader/pull/1
